# SPDX-FileCopyrightText: 2023 Holger Steinhaus
# SPDX-FileCopyrightText: 2023 Holger Steinhaus <hsteinhaus@gmx.de>
#
# SPDX-License-Identifier: MIT

substitutions:
  device_name: "battery-protect"
  friendly_name: Battery protect
  device_description: Simple current-loop based UVP/OVP protection circuit

esphome:
  name: ${device_name}
  comment: ${device_description}

esp8266:
  board: esp12e

logger:
#  level: VERBOSE

api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .wifi.home

web_server:
  port: 80
  ota: true
  
switch:
  - platform: gpio
    id: relay_1
    name: "OVP Relay"
    pin: GPIO4
  
sensor:
- platform: adc
  pin: A0
  name: voltage
  unit_of_measurement: 'V'
  filters:
    - offset: 0.
    - multiply: 30.

binary_sensor:
  - platform: gpio
    name: "Battery alarm loop"
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    filters:
    - delayed_on_off: 0.1s
    on_release:
      then:
        - switch.turn_on: relay_1
        - delay: 0.5s
        - switch.turn_off: relay_1
        
